# Generated by Django 3.2.6 on 2024-10-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PsudoTesting', '0004_expriment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expriment',
            name='text',
        ),
        migrations.AddField(
            model_name='expriment',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='expriment',
            name='text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expriment',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
