# Generated by Django 3.2.6 on 2024-10-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PsudoTesting', '0005_auto_20241017_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expriment',
            name='text2',
        ),
        migrations.AlterField(
            model_name='expriment',
            name='text1',
            field=models.TextField(),
        ),
    ]
