# Generated by Django 3.2.6 on 2024-10-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PsudoTesting', '0006_auto_20241017_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expriment',
            old_name='text1',
            new_name='text',
        ),
    ]
